env: local
racine: AppBundle:IndexController:indexAction

traduction:
    activate: no
    default: fr
    available:
        - fr

log:
    error : yes
    request : yes
    access : yes

routing:
    file: routing.yml