__ftp:
    path: Composants/Framework/Systems/FTP/Ftp
    action: ftpAction
__sql:
    path: Composants/Framework/Systems/SQL/Sql
    action: sqlAction
__console:
    path: Composants/Framework/Systems/Console/Console
    action: consoleAction