accueil:
    path: GameBundle:IndexController:IndexAction

deconnexion:
    path: GameBundle:DeconnexionController:deconnexionAction

inscription:
    path: GameBundle:InscriptionController:inscriptionAction

game:
    path: GameBundle:GameController:gameAction

contact:
    path: GameBundle:ContactController:contactAction

confContact:
    path: GameBundle:ContactController:confContactAction

aide:
    path: GameBundle:AideController:aideAction

admin:
    path: GameBundle:AdminController:adminAction

connexion:
    path: GameBundle:ConnexionController:connexionAction

carte:
    path: GameBundle:CarteController:carteAction

mouvement:
    path: GameBundle:MouvementController:showMouvAction

batiment:
    path: GameBundle:BatimentController:batimentAction

batConf:
    path: GameBundle:BatimentController:batConfAction

techno:
    path: GameBundle:TechnoController:technoAction